name: activity_recognition_flutter
description: Activity recognition plugin for Android and iOS.
version: 1.2.4
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master/packages


environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dk.cachet.activity_recognition_flutter
        pluginClass: ActivityRecognitionFlutterPlugin
      ios:
        pluginClass: ActivityRecognitionFlutterPlugin


