name: app_usage
description: View usage statistics of all applications on the phone (Android only).
version: 0.9.0
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master/packages/app_usage

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: cachet.plugins.appusage
    pluginClass: AppUsagePlugin

