name: app_usage
description: A new Flutter project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: cachet.plugins.appusage
    pluginClass: AppUsagePlugin

