name: flutter_foreground_service
description: Foreground service for the Android platform
version: 0.2.0
homepage: https://github.com/cph-cachet/flutter-plugins

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dk.cachet.flutter_foreground_service
        pluginClass: FlutterForegroundServicePlugin
      ios:
        pluginClass: FlutterForegroundServicePlugin