name: mobility_features
description: Real-time mobility feature calculation
version: 3.0.0+1
homepage: https://github.com/cph-cachet/flutter-plugins/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  simple_cluster: ^0.3.0
  stats: ^2.0.0
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: