name: noise
description: A Noise measurement plugin for Flutter. Uses a platform channel to read the noise, works for Android currently and eventually iOS.
version: 0.0.1
homepage: https://github.com/cph-cachet/flutter-plugins/tree/noise/packages/noise
author: CACHET Team <cph.cachet@gmail.com>

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.example.noise
    pluginClass: NoisePlugin

